version: '3.8'

services:
  express-api:
    build: ./express-api
    env_file: .env
    command: 'nodemon .'
    ports:
      - 3000:3000
    volumes:
      - ./express-api:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4.10
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081

volumes:
  node_modules:
  mongo_data:
